[build]
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  included_files = ["functions/*"]

[context.production]
  command = "npm start"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200