name: Bug Report 🐞
description: Create a report to help us fix a bug
labels: bug
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        ## Description
        Please provide a detailed description of the bug you encountered. 📝

  - type: input
    attributes:
      label: What did you expect to happen? 🤔
      placeholder: Describe what you expected to happen.

  - type: input
    attributes:
      label: What is the actual behavior? 😱
      placeholder: Describe the unexpected behavior.

  - type: input
    attributes:
      label: Steps to reproduce the behavior 🔄
      placeholder: Provide steps to reproduce the bug.

  - type: input
    attributes:
      label: What version of the project are you using? 📦
      placeholder: Include the version number if possible.

  - type: input
    attributes:
      label: Additional context 📸
      placeholder: Any other information (logs, screenshots, etc.)

